title: My Jekyll Site
description: A simple test site.
author: test
baseurl: "/Jekylltest" # This matches the --baseurl parameter
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
